<?php

namespace Database\Seeders;

use Botble\Base\Facades\MetaBox;
use Botble\Base\Supports\BaseSeeder;
use Botble\Page\Models\Page;
use Botble\Slug\Facades\SlugHelper;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\File;

class PageSeeder extends BaseSeeder
{
    public function run(): void
    {
        $this->uploadFiles('about');
        $this->uploadFiles('backgrounds');
        $this->uploadFiles('brands');
        $this->uploadFiles('homepage');
        $this->uploadFiles('work-process');
        $this->uploadFiles('contact');

        Page::query()->truncate();

        $stylePageDetail = [
            'breadcrumb' => 'style-1',
            'breadcrumb_color' => '#e0f0f6',
            'breadcrumb_background' => 'general/world-map.png',
            'breadcrumb_image' => 'general/favicon.png',
        ];

        $pages = [
            [
                'name' => 'Homepage 1',
                'content' =>
                    '[simple-slider key="home-slider"][/simple-slider]' .
                    '[brands title="We are trusted by major global brands" highlight_text="trusted" background_color="#E0F0F6" quantity="6" name_1="Alea" image_1="brands/alea.png" link_1="/contact-us" name_2="Creati" image_2="brands/creati.png" link_2="/contact-us" name_3="Land Ship" image_3="brands/land.png" link_3="/contact-us" name_4="Logis Delivery" image_4="brands/logis.png" link_4="/contact-us" name_5="Santos Logistic" image_5="brands/saltos.png" link_5="/contact-us" name_6="Truck" image_6="brands/truck.png" link_6="/contact-us"][/brands]' .
                    '[services title="What We Offer" description="Welcome to our transportation services agency. We are the best at our transportation service ever." button_label="Get a quote" button_link="/contact-us" background="backgrounds/bg-offer.png" left_shape_image="icons/quote.png" style="style-1" quantity="6" name_1="Sea Forwarding" image_1="icons/cargo-ship.png" description_1="We are professional in ocean freight with more than 12 years of experience and have shipped more than 100k shipments." link_1="/contact-us" name_2="Air Freight Forwarding" image_2="icons/plane.png" description_2="We are professional in ocean freight with more than 12 years of experience and have shipped more than 100k shipments." link_2="/contact-us" name_3="Land Transportation" image_3="icons/delivery.png" description_3="We are professional in ocean freight with more than 12 years of experience and have shipped more than 100k shipments." link_3="/contact-us" name_4="Warehouse & Distribution" image_4="icons/forklift.png" description_4="We are professional in ocean freight with more than 12 years of experience and have shipped more than 100k shipments." link_4="/contact-us" name_5="Railway Logistics" image_5="icons/train.png" description_5="We are professional in ocean freight with more than 12 years of experience and have shipped more than 100k shipments." link_5="/contact-us" name_6="Cross Border" image_6="icons/worldwide.png" description_6="We are professional in ocean freight with more than 12 years of experience and have shipped more than 100k shipments." link_6="/contact-us"][/services]' .
                    htmlentities('[information-1 title="We are proud of our workforce <br> and have worked hard." subtitle="Delivering Results for Industry Leaders" icon="general/favicon.png" left_background="homepage/img1.png" shape_image_horizontal="icons/icon1.png" shape_image_vertical="shapes/subtract.png" right_title="Fast shipping with the most modern technology" right_description="Over the years, we have worked together to expand our network of partners to deliver reliability and consistency. We’ve also made significant strides to tightly integrate technology with our processes, giving our clients greater visibility into every engagement." feature_1="Task tracking" feature_2="Create task dependencies" feature_3="Task visualization" feature_4="Hare files, discuss" feature_5="Meet deadlines faster" feature_6=" Track time spent on project" button_label_1="Apple Store" button_url_1="https://apps.apple.com/us/app/" button_image_1="general/appstore-btn.png" button_label_2="Google Play" button_url_2="https://play.google.com/store/apps" button_image_2="general/google-play-btn.png" style="style-1" quantity="6"][/information-1]') .
                    htmlentities('[information-2 left_background="shapes/bg-touch.png" right_background="homepage/port.png" title="Proud to Deliver <br> Excellence Every Time" badge_text="Get in touch" description="Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit laborum — semper quis lectus nulla. Interactively transform magnetic growth strategies whereas prospective ‘‘outside the box’’ thinking." button_label="Contact Us" button_url="/contact-us" link_label="Learn More" link_url="/contact-us" style="style-1" quantity="2" title_1="Boost your sale" image_1="icons/chart.png" description_1="The latest design trends meet hand-crafted templates." title_2="Introducing New Features" image_2="icons/feature3.png" description_2="The latest design trends meet hand-crafted templates."][/information-2]') .
                    '[how-it-works title="How It Works" description="You choose the cities where you’d like to deliver. All deliveries are within a specific service area and delivery services vary by location. Whatever the mode or requirement, we will find and book the ideal expedited shipping solution to ensure a timely delivery." background_color="#034460" title_direction="center" youtube_video_url="https://www.youtube.com/watch?v=Y1t6rjWYNro" icon="general/favicon.png" inner_background="general/world-map.png" left_background="homepage/how-it-work.png" left_title="We have 25 years experience in this passion" left_description="There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour" left_icon="icons/play.png" style="style-1" quantity="5" title_1=" Customer places order" description_1="Inspection and quality check of goods" image_1="icons/order.png" title_2="Payment successful" description_2="Payoneer, Paypal, or Visa master card" image_2="icons/payment.png" title_3="Warehouse receives order" description_3="Check the accuracy of the goods." image_3="icons/warehouse.png" title_4="Item picked, packed & shipped" description_4="Ship the goods to a local carrier" image_4="icons/picked.png" title_5="Delivered & Measure success" description_5="Update order status on the system" image_5="icons/delivery.png"][/how-it-works]' .
                    htmlentities('[testimonials title="What our customers are saying" description="Hear from our users who have saved thousands on their <br> Startup and SaaS solution spend." limit="4" background="homepage/ship.png" right_background="shapes/bg-testimonial.png" shape_image="icons/quotation.png"][/testimonials]') .
                    '[projects title="What We Have Done" description="Check out some of the projects we’ve completed with our amazing partners." button_label="View All Projects" button_url="/contact-us" background="shapes/bg-what-done.png" style="style-1" quantity="4" name_1="Air Freight" description_1="Our Air Freight project soared above expectations, showcasing our expertise in urgent deliveries. We provided rapid, global air transportation solutions that met critical timelines. When time is of the essence." image_1="homepage/img.png" url_1="/contact-us" name_2="Sea Freight" description_2="Our Sea Freight project stands as a testament to our proficiency in navigating international waters. Seamlessly managing complex logistics, we delivered goods across continents with efficiency and reliability." image_2="homepage/img2.png" url_2="/contact-us" name_3="Trucking" description_3="In our Trucking project, we transformed roadways into avenues of precision and punctuality. With a fleet of modern vehicles and a team of skilled drivers, we ensured swift and secure deliveries nationwide. Your cargo’s journey." image_3="homepage/img3.png" url_3="/contact-us" name_4="Warehouse" description_4="In our Warehouse project, we excelled in storage and distribution. With state-of-the-art facilities and meticulous inventory management, we safeguarded your assets while streamlining the supply chain. Your goods found." image_4="homepage/img4.png" url_4="/contact-us"][/projects]' .
                    htmlentities('[request-quote title="World’s Leading Companies <br> For Over 80 Years." description="A big opportunity for your business growth. Delivering Results for Industry Leaders. We are <br> proud of our work for and have worked hard." background="homepage/container.png" quantity="4" image_1="icons/handover.png" number_1="+ 380,000" title_1="Parcels Shipped Safely" image_2="icons/cities.png" number_2="+ 120,000" title_2="Cities Served Worldwide" image_3="icons/client.png" number_3="+2280" title_3="Satisfied Clients" image_4="icons/company.png" number_4="+ 1200" title_4="Company We Help" form_title="Calculate Shipping" form_description="Please Fill All Inquiry To Get Your Total Price." inner_background="shapes/bg-contact.png" form_background="homepage/img-contact.png" link_label="Contact Us" link_url="/contact-us"][/request-quote]') .
                    htmlentities('[pricing title="Choose The Best Plan" description="Pick your plan. Change whenever you want.<br>No switching fees between packages" style="style-1" package_ids="1,2,4" number_of_packages_per_line="3" left_background="backgrounds/bg-plan-left.png" right_background="backgrounds/bg-plan-right.png"][/pricing]') .
                    '[faqs title="FAQs" description="Feeling inquisitive? Have a read through some of our FAQs or contact our supporters for help." gallery_id="7" category_ids="1,2" expand_first_time="1" bottom_title="Need more help?" button_label="Contact Us" button_url="/contact-us" link_label="Learn More" link_url="/contact-us"][/faqs]' .
                    '[call-to-action title="Create your next Project with Us" subtitle="Have any ideas in your mind?" background="backgrounds/bg-get-quote.png" button_label="GET A QUOTE" button_url="/contact-us"][/call-to-action]' .
                    '[news title="Latest News" description="The latest information about shipping services and our promotions." type="latest"][/news]' .
                    '[map logo="general/logo.png" address="4517 Washington Ave. Manchester, Kentucky 39495" phone="+01-246-357 (Any time 24/7)" email="contact@transp.eu.com" opening_hours="Hours: 8:00 - 17:00, Mon - Sat"][/map]'
                ,
                'template' => 'default',
                'metadata' => [
                    'hide_pre_footer_sidebar' => true,
                ],
            ],
            [
                'name' => 'Homepage 2',
                'content' =>
                    htmlentities('[hero-banner title="Taking Logistics to <br> Another Leve" subtitle="Full Sustainable Cargo Solutions" description="Representative logistics operator providing full range of service in the sphere of customs <br> clearance and transportation worldwide." banner_image="homepage/banner-2.png" platform_google_play_url="https://play.google.com/" platform_google_play_logo="general/google-play-btn.png" platform_apple_store_url="https://www.apple.com/store" platform_apple_store_logo="general/appstore-btn.png" style="style-2" quantity="3" title_1="Air Freight Forwarding" description_1="We are professional in ocean freight with more than 12 years of experience and have shipped more than 100k shipments." image_1="icons/plane.png" label_1="View detail" action_1="/contact-us" title_2="Land Transportation" description_2="We are professional in ocean freight with more than 12 years of experience and have shipped more than 100k shipments." image_2="icons/delivery.png" label_2="View detail" action_2="/contact-us" title_3="Sea Forwarding" description_3="We are professional in ocean freight with more than 12 years of experience and have shipped more than 100k shipments." image_3="icons/cargo-ship.png" label_3="View detail" action_3="/contact-us"][/hero-banner]') .
                    '[site-statistics title="Why Choose Us" subtitle="Let the numbers speak for themselves." image="homepage/img-why.png" background_icon="shapes/bg-why.png" mini_icon_bottom="icons/quote.png" button_label="View All Projects" button_url="/contact-us" style="style-1" quantity="4" title_1="Delivered packages." data_1="380" unit_1="K" description_1="We strongly support best practice sharing across our operations around the world and across various industrial sectors." title_2="Countries covered" data_2="150" unit_2="+" description_2="We strongly support best practice sharing across our operations around the world and across various industrial sectors." title_3="Satisfied Clients" data_3="6800" description_3="We strongly support best practice sharing across our operations around the world and across various industrial sectors." title_4="Tons of goods" data_4="120" unit_4="K" description_4="We strongly support best practice sharing across our operations around the world and across various industrial sectors."][/site-statistics]' .
                    '[request-quote title="Fast shipping with the most modern technology" description="Over the years, we have worked together to expand our network of partners to deliver reliability and consistency. We’ve also made significant strides to tightly integrate technology with our processes, giving our clients greater visibility into every engagement." background="shapes/bg-quote.png" background_color="#E0F0F6" style="style-5" quantity="4" image_1="icons/chart.png" title_1="Boost your sale" description_1="The latest design trends meet hand-crafted templates." image_2="icons/chart.png" title_2="Boost your sale" description_2="The latest design trends meet hand-crafted templates." image_3="icons/feature.png" title_3="Introducing New Features" description_3="The latest design trends meet hand-crafted templates." image_4="icons/feature2.png" title_4="Introducing New Features" description_4="The latest design trends meet hand-crafted templates." form_title="Request a Quote" form_description="Please Fill All Inquiry To Get Your Total Price."][/request-quote]' .
                    '[get-in-touch-with-us title="We take care about transportation for your business" subtitle="GET IN TOUCH WITH US" image="homepage/img-info-3.png" box_info_left_title="Warehousing" box_info_left_description="We are professional in ocean freight with more than 12 years of experience and have shipped more than 100k shipments." box_info_left_button_label="View Details" box_info_left_button_url="/contact-us" box_info_bottom_title="We have 25 years experience in this passion" box_info_bottom_description="There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour" box_info_bottom_icon="icons/play.png" quantity="2" title_1="Great support 24/7" image_1="icons/chart.png" description_1="The latest design trends meet hand-crafted templates." title_2="Safe Packing" image_2="homepage/feature2.png" description_2="The latest design trends meet hand-crafted templates."][/get-in-touch-with-us]' .
                    '[pricing title="Pricing Plan" description="Pick your plan. Change whenever you want. No switching fees between packages" style="style-2" package_ids="1,2,3,4" number_of_packages_per_line="4" left_background="backgrounds/bg-plan-left.png" right_background="backgrounds/bg-plan-right.png"][/pricing]' .
                    '<div class="line-border"></div>' .
                    '[teams title="Meet Our Team" description="Welcome to our transportation services agency. We are the best at our trans-deportation service ever." team_ids="1,2,3,4"][/teams]' .
                    '[brands title="We are trusted by major global brands" highlight_text="trusted" quantity="6" name_1="Alea" image_1="brands/alea.png" link_1="https://alea.gov" name_2="Creati" image_2="brands/creati.png" link_2="/contact-us" name_3="Land Ship" image_3="brands/land.png" link_3="/contact-us" name_4="Logis Delivery" image_4="brands/logis.png" link_4="/contact-us" name_5="Santos Logistic" image_5="brands/saltos.png" link_5="/contact-us" name_6="Truck" image_6="brands/truck.png" link_6="/contact-us"][/brands]' .
                    htmlentities('[testimonials title="Testimonials" description="Hear from our users who have saved thousands on their <br> Startup and SaaS solution spend." limit="4" background_color="#FFFFFF" prefix_title_icon="general/favicon.png" style="style-4"][/testimonials]') .
                    htmlentities('[our-features title_primary="Global Shipping Partner To World’s <br> Famous Companies" title="Why choose us" subtitle="Our Features" description="Sustainability is an increasingly important factor for many customers when choosing a shipping company. Your shipping company can stand out by demonstrating a commitment to sustainable practices, such as using energy-efficient vehicles, reducing waste, and offsetting carbon emissions." background_color="#E0F0F6" image="homepage/img-info-4.png" button_primary_label="Contact Us" button_primary_url="/contact-us" button_secondary_label="Learn More" button_secondary_url="/about-us" quantity="8" title_1="Reliable and Timely Deliveries" title_2="Cost-Effective Shipping Options" title_3="Exceptional Customer Service" title_4="Flexibility and Customization" title_5="Advanced Tracking Systems" title_6="Commitment to Sustainability" title_7="International Shipping Expertise" title_8="Insurance and Liability Coverage"][/our-features]') .
                    '[news title="Our Blog & Insights" description="The latest information about shipping services and our promotions" type="featured" limit="4"][/news]'
                ,
                'template' => 'default',
            ],
            [
                'name' => 'Homepage 3',
                'content' =>
                    '[hero-banner title="Moving Your Products Across All Borders" description="Over the years, we have worked together to expand our network of partners to deliver reliability and consistency. We’ve also made significant strides to tightly integrate technology with our processes, giving our clients greater visibility into every engagement." background_color="#E0F0F6" banner_image="homepage/banner-3.png" shape_icon="shapes/bg-union.png" youtube_video_url="https://www.youtube.com/watch?v=Y1t6rjWYNro" button_label="How it works?" button_primary_url="/contact-us" button_primary_label="Contact Us" style="style-3" quantity="3" title_1="Parcels Shipped" data_1=" 380,000" image_1="icons/delivery.png" title_2="Cities Worldwide" data_2="12,000" image_2="icons/forklift.png" title_3="Satisfied Clients" data_3=" 2280" unit_3="K" image_3="icons/cargo-ship.png"][/hero-banner]' .
                    htmlentities('[information-2 left_background="homepage/img-info-5.png" right_background="homepage/img-info-5-2.png" center_icon="icons/certified.png" title="Proud to Deliver <br> Excellence Every Time" badge_text="Get in touch" description="Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit laborum — semper quis lectus nulla. Interactively transform magnetic growth strategies whereas prospective ‘‘outside the box’’ thinking." button_label="Contact Us" button_url="/contact-us" link_label="Learn More" link_url="/contact-us" style="style-2" quantity="2" title_1="Boost your sale" image_1="icons/chart.png" description_1="The latest design trends meet hand-crafted templates." title_2="Introducing New Features" image_2="icons/feature3.png" description_2="The latest design trends meet hand-crafted templates."][/information-2]') .
                    '[brands title="We are trusted by major global brands" highlight_text="trusted" background_color="#E0F0F6" quantity="6" name_1="Alea" image_1="brands/alea.png" link_1="/contact-us" name_2="Creati" image_2="brands/creati.png" link_2="/contact-us" name_3="Land Ship" image_3="brands/land.png" link_3="/contact-us" name_4="Logis Delivery" image_4="brands/logis.png" link_4="/contact-us" name_5="Santos Logistic" image_5="brands/saltos.png" link_5="/contact-us" name_6="Truck" image_6="brands/truck.png" link_6="/contact-us"][/brands]' .
                    '[what-we-offer title="What We Offer" description="Welcome to our transportation services agency. We are the best at our transportation service ever." button_label="Get a quote" button_url="/contact-us" quantity="4" title_1="Sea Forwarding" image_1="services/service1.png" icon_1="icons/delivery.png" description_1="We offer specialized departments for continental transports." title_2="Air Freight Forwarding" image_2="services/service2.png" icon_2="icons/delivery.png" description_2="We offer specialized departments for continental transports." title_3="Land Transportation" image_3="services/service3.png" icon_3="icons/plane.png" description_3="We offer specialized departments for continental transports." title_4="Railway Logistics" image_4="services/service4.png" icon_4="icons/train.png" description_4="We offer specialized departments for continental transports."][/what-we-offer]' .
                    '[site-statistics title="We take care about transportation for your business" highlight_text="transportation" image="backgrounds/bg-whychooseus.png" button_label="View All Projects" button_url="/contact-us" style="style-2" quantity="4" title_1="Delivered packages." data_1="380" unit_1="K" title_2="Countries covered" data_2="150" unit_2="+" title_3="Satisfied Clients" data_3="6800" title_4="Tons of goods" data_4="120" unit_4="K"][/site-statistics]' .
                    '[who-we-are title="We’re the world’s leading shipping service provider" subtitle="Who We Are?" description="Over the years, we have worked together to expand our network of partners to deliver reliability and consistency. We’ve also made significant strides to tightly integrate technology with our processes, giving our clients greater visibility into every engagement." image="homepage/img-info-6.png" youtube_video_url="https://www.youtube.com/watch?v=v2qeqkKgw7U" button_label="How it works ? Watch video tour" button_icon="icons/play.png" style="style-1" quantity="4" title_1="Boost your sale" icon_1="icons/chart.png" description_1="The latest design trends meet hand-crafted templates." title_2="Boost your sale" icon_2="icons/chart.png" description_2="The latest design trends meet hand-crafted templates." title_3="Introducing New Features" icon_3="icons/feature.png" description_3="The latest design trends meet hand-crafted templates." title_4="Introducing New Features" icon_4="icons/feature2.png" description_4="The latest design trends meet hand-crafted templates."][/who-we-are]' .
                    htmlentities('[projects title="Our latest completed and <br> running projects" description="Delivering Results for Industry Leaders" button_label="View All Projects" button_url="/contact-us" prefix_title_icon="general/favicon.png" style="style-2" quantity="4" name_1="Air Freight" description_1="Our Air Freight project soared above expectations, showcasing our expertise in urgent deliveries. We provided rapid, global air transportation solutions that met critical timelines. When time is of the essence." image_1="homepage/img.png" url_1="/contact-us" name_2="Sea Freight" description_2="Our Sea Freight project stands as a testament to our proficiency in navigating international waters. Seamlessly managing complex logistics, we delivered goods across continents with efficiency and reliability." image_2="homepage/img2.png" url_2="/contact-us" name_3="Trucking" description_3="In our Trucking project, we transformed roadways into avenues of precision and punctuality. With a fleet of modern vehicles and a team of skilled drivers, we ensured swift and secure deliveries nationwide. Your cargo’s journey." image_3="homepage/img3.png" url_3="/contact-us" name_4="Warehouse" description_4="In our Warehouse project, we excelled in storage and distribution. With state-of-the-art facilities and meticulous inventory management, we safeguarded your assets while streamlining the supply chain. Your goods found." image_4="homepage/img4.png" url_4="/contact-us"][/projects]') .
                    '[testimonials title="Testimonials" description="Hear from our users who have saved thousands on their Startup and SaaS solution spend. Quo nostrum praesentium At ratione iusto qui labore nesciunt ad architecto dolor est odio molestias non molestiae incidunt in praesentium odit." limit="4" background="backgrounds/bg-testimonial-3.png" prefix_title_icon="general/favicon.png" button_primary_url="/contact-us" button_primary_label="Contact Us" button_secondary_url="/about-us" button_secondary_label="Learn More" style="style-2"][/testimonials]' .
                    '[request-quote background_color="#E0F0F6" style="style-3" quantity="6" image_1="icons/order.png" title_1="Customer places order" description_1="Inspection and quality check of goods" image_2="icons/payment.png" title_2="Payment successful" description_2="Payoneer, Paypal, or Visa master card" image_3="icons/warehouse.png" title_3="Warehouse receives order" description_3="Check the accuracy of the goods." image_4="icons/vespa.png" title_4="Item picked, packed & shipped" description_4="Ship the goods to a local carrier" image_5="icons/delivery.png" title_5=" Delivered & Measure success" description_5="Update order status on the system" form_title="Request a Quote" form_description="Please Fill All Inquiry To Get Your Total Price." link_label="Contact Us" link_url="/contact-us"][/request-quote]' .
                    '[faqs title="FAQs" description="Feeling inquisitive? Have a read through some of our FAQs or contact our supporters for help." gallery_id="7" category_ids="1,2" expand_first_time="1" bottom_title="Need more help?" button_label="Contact Us" button_url="/contact-us" link_label="Learn More" link_url="/contact-us"][/faqs]' .
                    '[news title="Our Blog & Insights" description="The latest information about shipping services and our promotions" type="featured" limit="3"][/news]'
                ,
                'template' => 'default',
                'metadata' => [
                    'header_style' => 'style-2',
                ],
            ],
            [
                'name' => 'Homepage 4',
                'content' =>
                    htmlentities('[hero-banner title="Worldwide shipping and <br> professional solutions" subtitle="Logistics & Transportation" description="Our experienced team of problem solvers and a commitment to always align with <br> our client’s business goals and objectives is what drives mutual success." background_color="#E0F0F6" banner_image="homepage/banner-4.png" youtube_video_url="https://www.youtube.com/watch?v=Y1t6rjWYNro&t=1s" button_label="How it works?" button_primary_url="/contact-us" button_primary_label="Calculate Package" style="style-4" quantity="4" title_1="Air Freight Forwarding" description_1="We are professional in ocean freight with more than 12 years of experience and have shipped more than 100k shipments." image_1="icons/plane.png" label_1="View detail" action_1="/contact-us" title_2="Land Transportation" description_2="We are professional in ocean freight with more than 12 years of experience and have shipped more than 100k shipments." image_2="icons/delivery.png" label_2="View detail" action_2="/contact-us" title_3="Sea Forwarding" description_3="We are professional in ocean freight with more than 12 years of experience and have shipped more than 100k shipments." image_3="icons/cargo-ship.png" label_3="View detail" action_3="/contact-us" title_4="Air Freight Forwarding" description_4="We are professional in ocean freight with more than 12 years of experience and have shipped more than 100k shipments." image_4="icons/plane.png"][/hero-banner]') .
                    htmlentities('[information-1 title="Globally Connected by <br> Large Network" subtitle="Who We Are?" description="We strive to become pioneers in the field, providing first quality and cost-effective service, and smart solutions to the market. Our 30 years’ experience in the shipping, transport and logistics industry is our strength, which support us to deliver our promises to our customers." left_background="homepage/img-info-7.png" shape_image_horizontal="icons/shape-icon.png" shape_image_vertical="shapes/bg-info-7.png" button_label_1="Apple Store" button_url_1="https://apps.apple.com/us/app/" button_image_1="general/appstore-btn.png" button_label_2="Google Play" button_url_2="https://play.google.com/store/apps" button_image_2="general/google-play-btn.png" style="style-2" quantity="2" title_1="Tracking Moving" icon_1="icons/chart.png" description_1="The latest design trends meet hand-crafted templates." title_2="24/7 Support" icon_2="icons/support.png" description_2="The latest design trends meet hand-crafted templates."][/information-1]') .
                    '[testimonial-single title="Testimonials" description="Hear from our users who have saved thousands on their Startup and SaaS solution spend." image="homepage/img-testimonial-4.png" background_shape="shapes/bg-testimonial-4.png" box_info_title="Satisfieds" box_info_description="We always strive to serve our customers in the best way. " box_info_label="View Details" box_info_action="/contact-us" testimonial_id="1"][/testimonial-single]' .
                    htmlentities('[how-it-works title="How It Works" description="You choose the cities where you’d like to deliver. All deliveries are within a specific service area and delivery services vary by location. Whatever the mode or requirement, we will find and book the ideal expedited shipping solution to ensure a timely delivery." background_color="#034460" title_direction="start" youtube_video_url="https://www.youtube.com/watch?v=v2qeqkKgw7U" button_label="How it works ? <br> Watch video tour" button_icon="icons/play-icon.png" icon="general/favicon.png" inner_background="backgrounds/bg-how-it-work.png" left_background="homepage/how-it-work.png" left_title="We have 25 years experience in this passion" left_description="There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour" left_icon="icons/play.png" style="style-2" quantity="5" title_1=" Customer places order" description_1="Inspection and quality check of goods" image_1="icons/order.png" title_2="Payment successful" description_2="Payoneer, Paypal, or Visa master card" image_2="icons/payment.png" title_3="Warehouse receives order" description_3="Check the accuracy of the goods." image_3="icons/warehouse.png" title_4="Item picked, packed & shipped" description_4="Ship the goods to a local carrier" image_4="icons/picked.png" title_5="Delivered & Measure success" description_5="Update order status on the system" image_5="icons/delivery-2.png"][/how-it-works]') .
                    '[projects title="What We Have Done" description="Check out some of the projects we’ve completed with our amazing partners." button_label="View All Projects" button_url="/contact-us" quantity="6" name_1="Air Freight" description_1="Our Air Freight project soared above expectations, showcasing our expertise in urgent deliveries. We provided rapid, global air transportation solutions that met critical timelines. When time is of the essence." image_1="homepage/img.png" url_1="/contact-us" name_2="Sea Freight" description_2="Our Sea Freight project stands as a testament to our proficiency in navigating international waters. Seamlessly managing complex logistics, we delivered goods across continents with efficiency and reliability." image_2="homepage/img2.png" url_2="/contact-us" name_3="Trucking" description_3="In our Trucking project, we transformed roadways into avenues of precision and punctuality. With a fleet of modern vehicles and a team of skilled drivers, we ensured swift and secure deliveries nationwide. Your cargo’s journey." image_3="homepage/img3.png" url_3="/contact-us" name_4="Warehouse" description_4="In our Warehouse project, we excelled in storage and distribution. With state-of-the-art facilities and meticulous inventory management, we safeguarded your assets while streamlining the supply chain. Your goods found." image_4="homepage/img4.png" url_4="/contact-us"][/projects]' .
                    '[who-we-are title="We are the world’s leading shipping service provider" subtitle="Who We Are?" description="Over the years, we have worked together to expand our network of partners to deliver reliability and consistency. We’ve also made significant strides to tightly integrate technology with our processes, giving our clients greater visibility into every engagement." image="homepage/img-info-6.png" youtube_video_url="https://www.youtube.com/watch?v=v2qeqkKgw7U" button_label="How it works ? Watch video tour" button_icon="icons/play.png" style="style-1" quantity="4" title_1="Boost your sale" icon_1="icons/chart.png" description_1="The latest design trends meet hand-crafted templates." title_2="Boost your sale" icon_2="icons/chart.png" description_2="The latest design trends meet hand-crafted templates." title_3="Introducing New Features" icon_3="icons/feature.png" description_3="The latest design trends meet hand-crafted templates." title_4="Introducing New Features" icon_4="icons/feature2.png" description_4="The latest design trends meet hand-crafted templates."][/who-we-are]' .
                    '<div class="line-border mb-30 mt-70"></div>' .
                    '[request-quote title="Fast shipping with the most modern technology" description="Over the years, we have worked together to expand our network of partners to deliver reliability and consistency. We’ve also made significant strides to tightly integrate technology with our processes, giving our clients greater visibility into every engagement." background="shapes/bg-quote.png" background_color="#E0F0F6" style="style-5" quantity="4" image_1="icons/chart.png" title_1="Boost your sale" description_1="The latest design trends meet hand-crafted templates." image_2="icons/chart.png" title_2="Boost your sale" description_2="The latest design trends meet hand-crafted templates." image_3="icons/feature.png" title_3="Introducing New Features" description_3="The latest design trends meet hand-crafted templates." image_4="icons/feature2.png" title_4="Introducing New Features" description_4="The latest design trends meet hand-crafted templates." form_title="Request a Quote" form_description="Please Fill All Inquiry To Get Your Total Price."][/request-quote]' .
                    '[why-choose-us title="Why choose us" subtitle="Our Features" description="Sustainability is an increasingly important factor for many customers when choosing a shipping company. Your shipping company can stand out by demonstrating a commitment to sustainable practices, such as using energy-efficient vehicles, reducing waste, and offsetting carbon emissions." ticked_line="Reliable and Timely Deliveries, Advanced Tracking Systems, Cost-Effective Shipping Options, Commitment to Sustainability, Exceptional Customer Service, International Shipping Expertise, Flexibility and Customization, Insurance and Liability Coverage" button_primary_label="Contact Us" button_primary_url="/contact-us" button_secondary_label="Learn More" button_secondary_url="/contact-us" style="style-1" quantity="4" title_1="Shipping Options" icon_1="icons/container.png" description_1="Tailored routes for versatile shipments, offering expedited and budget-friendly choices." title_2="Timely Deliveries" icon_2="icons/stopwatch.png" description_2="Precision planning and monitoring ensure on-time deliveries, a competitive edge for you." title_3="Customer Service" icon_3="icons/24-hours.png" description_3="Proactive solutions from our team, transforming challenges into satisfaction and support." title_4="Tracking Systems" icon_4="icons/pallet.png" description_4="Visibility at every stage, bridging distance through real-time insights for peace of mind."][/why-choose-us]' .
                    '[brands title="We are trusted by major global brands" highlight_text="trusted" quantity="6" name_1="Alea" image_1="brands/alea.png" link_1="https://alea.gov" name_2="Creati" image_2="brands/creati.png" link_2="https://creati.com" name_3="Land Ship" image_3="brands/land.png" link_3="https://landship.com" name_4="Logis Delivery" image_4="brands/logis.png" link_4="http://logisdelivery.com" name_5="Santos Logistic" image_5="brands/saltos.png" link_5="http://santoslogistic.com" name_6="Truck" image_6="brands/truck.png" link_6="https://truck.com"][/brands]' .
                    '[pricing title="Pricing Plan" description="Pick your plan. Change whenever you want. No switching fees between packages" style="style-2" package_ids="1,2,3,4" number_of_packages_per_line="4" left_background="backgrounds/bg-plan-left.png" right_background="backgrounds/bg-plan-right.png"][/pricing]' .
                    '[news title="Our Blog & Insights" description="The latest information about shipping services and our promotions." type="latest"][/news]'
                ,
                'template' => 'default',
            ],
            [
                'name' => 'About Us',
                'template' => 'default',
                'metadata' => [
                    'breadcrumb' => 'style-2',
                    'breadcrumb_color' => '#034460',
                    'breadcrumb_background' => 'backgrounds/bg-ship-banner.png',
                ],
                'description' => htmlentities('We have been pioneering the industry in Europe for 20 years, and delivering value <br> products within given timeframe, every single time.'),
                'content' =>
                    '[about-information-1 title="Simplifying complex shipping challenges with innovative solutions" description="Logistics companies are essential to the smooth functioning of global supply chains. They offer a range of services such as transportation, warehousing, inventory management, and distribution to businesses across different industries. The role of logistics companies has become increasingly important in recent years due to the growth of e-commerce and global trade." button_primary_label="Calculate Package" button_primary_url="/contact-us" icon="icons/play.png" icon_url="https://www.youtube.com/watch?v=v2qeqkKgw7U" image_1="about/img-about-1-1.png" image_2="about/img-about-1-2.png" image_3="about/img-about-1-3.png" floating_icon="icons/quote-2.png"][/about-information-1]' .
                    '[about-information-2 quantity="3" badge_1="Mission" title_1="Globally Connected by Large Network" description_1="At Logistic TransP, our mission is to provide our clients with exceptional transportation services that meet and exceed their expectations. We aim to be the most reliable, efficient, and cost-effective transportation provider in the industry." image_1="about/img-about-2-1.png" icon_for_feature_1_1="icons/chart.png" feature_1_1="Affordable Cost" feature_description_1_1="The latest design trends meet hand-crafted templates." icon_for_feature_2_1="icons/feature3.png" feature_2_1="Short Time Delivery" feature_description_2_1="The latest design trends meet hand-crafted templates." badge_2="History" title_2="Globally Connected by Large Network" description_2="Logistic TransP was founded in 2005 by a group of transportation professionals who saw an opportunity to provide a better level of service to businesses. Since our founding, we have grown to become a leading transportation provider, with a presence in over 30 countries around the world." image_2="about/img-about-2-2.png" button_primary_label_2="Contact Us" button_primary_url_2="/contact-us" button_secondary_label_2="Learn More" button_secondary_url_2="/contact-us" badge_3="Our Partners" title_3="We have established strong relationships with our partners" description_3="We strive to become pioneers in the field, providing first quality and cost-effective service, and smart solutions to the market. Our 30 years’ experience in the shipping, transport and logistics industry is our strength, which support us to deliver our promises to our customers." image_3="about/img-about-2-3.png" platform_google_play_url_3="https://store.google.com/regionpicker" platform_google_play_logo_3="general/google-play-btn.png" platform_apple_store_url_3="https://www.apple.com/vn/app-store/" platform_apple_store_logo_3="general/appstore-btn.png"][/about-information-2]' .
                    htmlentities('[information-2 left_background="shapes/bg-touch.png" right_background="homepage/img-info-2.png" title="Proud to Deliver <br> Excellence Every Time" badge_text="Get in touch" description="Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit laborum — semper quis lectus nulla. Interactively transform magnetic growth strategies whereas prospective ‘‘outside the box’’ thinking." button_label="Contact Us" button_url="/contact-us" link_label="Learn More" link_url="/contact-us" style="style-1" quantity="2" title_1="Boost your sale" image_1="icons/chart.png" description_1="The latest design trends meet hand-crafted templates." title_2="Introducing New Features" image_2="icons/feature3.png" description_2="The latest design trends meet hand-crafted templates."][/information-2]') .
                    '[teams title="Meet Our Team" description="Welcome to our transportation services agency. We are the best at our trans-deportation service ever." team_ids="1,2,3,4"][/teams]' .
                    '[brands title="We are trusted by major global brands" highlight_text="trusted" quantity="6" name_1="Alea" image_1="brands/alea.png" link_1="https://alea.gov" name_2="Creati" image_2="brands/creati.png" link_2="/contact-us" name_3="Land Ship" image_3="brands/land.png" link_3="/contact-us" name_4="Logis Delivery" image_4="brands/logis.png" link_4="/contact-us" name_5="Santos Logistic" image_5="brands/saltos.png" link_5="/contact-us" name_6="Truck" image_6="brands/truck.png" link_6="/contact-us"][/brands]' .
                    htmlentities('[testimonials title="Testimonials" description="Hear from our users who have saved thousands on their <br> Startup and SaaS solution spend." limit="4" background_color="#034460" style="style-4"][/testimonials]') .
                    '[call-to-action title="Create your next Project with Us" subtitle="Have any ideas in your mind?" background="backgrounds/bg-get-quote.png" button_label="GET A QUOTE" button_url="/request-a-quote"][/call-to-action]' .
                    '[news title="Our Blog & Insights" description="The latest information about shipping services and our promotions" type="latest"][/news]'
                ,
            ],
            [
                'name' => 'Services',
                'content' =>
                    htmlentities('[our-services title="Our Services" subtitle="What we offer" description="We have been pioneering the industry in Europe for 20 years, and delivering value <br> products within given timeframe, every single time." service_ids="1,2,3,4,5,6,7"][/our-services]') .
                    htmlentities('[information-2 left_background="homepage/img-info-5.png" right_background="homepage/img-info-5-2.png" center_icon="icons/certified.png" title="Proud to Deliver <br> Excellence Every Time" badge_text="Get in touch" description="Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit laborum — semper quis lectus nulla. Interactively transform magnetic growth strategies whereas prospective ‘‘outside the box’’ thinking." button_label="Contact Us" button_url="/contact-us" link_label="Learn More" link_url="/contact-us" style="style-2" quantity="2" title_1="Boost your sale" image_1="icons/chart.png" description_1="The latest design trends meet hand-crafted templates." title_2="Introducing New Features" image_2="icons/feature3.png" description_2="The latest design trends meet hand-crafted templates."][/information-2]') .
                    '[site-statistics title="We take care about transportation for your business" highlight_text="transportation" image="backgrounds/bg-whychooseus.png" button_label="View All Projects" button_url="/contact-us" style="style-2" quantity="4" title_1="Delivered packages." data_1="380,000" title_2="Countries covered" data_2="150,000" title_3="Satisfied Clients" data_3="68,000" title_4="Tons of goods" data_4="120,000"][/site-statistics]' .
                    htmlentities('[request-quote title="World’s Leading Companies <br> For Over 80 Years." description="A big opportunity for your business growth. Delivering Results for Industry Leaders. We are <br> proud of our work for and have worked hard." background="shapes/bg-requestquote-3.png" background_color="#E0F0F6" style="style-3" quantity="5" image_1="icons/order.png" title_1="Customer places order" description_1="Inspection and quality check of goods" image_2="icons/payment.png" title_2="Payment successful" description_2="Payoneer, Paypal, or Visa master card" image_3="icons/warehouse.png" title_3="Warehouse receives order" description_3="Check the accuracy of the goods." image_4="icons/picked.png" title_4="Item picked, packed & shipped" description_4="Ship the goods to a local carrier" image_5="icons/delivery.png" title_5="Delivered & Measure success" description_5="Update order status on the system" form_title="Request a Quote" form_description="Please Fill All Inquiry To Get Your Total Price." inner_background="shapes/bg-contact.png" form_background="homepage/img-contact.png" link_label="Contact Us" link_url="/contact-us"][/request-quote]') .
                    htmlentities('[pricing title="Pricing Plan" description="Pick your plan. Change whenever you want. No switching fees between packages" style="style-2" package_ids="1,2,3,4" number_of_packages_per_line="4"][/pricing]') .
                    '<div class="line-border"></div>' .
                    '[faqs title="FAQs" description="Feeling inquisitive? Have a read through some of our FAQs or contact our supporters for help." gallery_id="7" category_ids="1,2" expand_first_time="1" bottom_title="Need more help?" button_label="Contact Us" button_url="/contact-us" link_label="Learn More" link_url="/contact-us"][/faqs]'
                ,
                'template' => 'default',
            ],
            [
                'name' => 'Track Your Parcel',
                'content' =>
                    htmlentities('[track-your-parcel title=" Package tracking is easy <br> with order number" description="Track packages from China, US Post, Canada Post, Royal Mail, Deutsche Post, <br> Aliexpress, UPS, Shein, FedEx, Pitney Bowes, eBay, Amazon" platform_google_play_url="https://play.google.com/" platform_google_play_logo="general/google-play-btn.png" platform_apple_store_url="https://www.apple.com/store" platform_apple_store_logo="general/appstore-btn.png"][/track-your-parcel]') .
                    '[who-we-are title="Any post office tracking" subtitle="International tracking for" description="Our tracking system is updated in real-time, so you can rest assured that you are getting the most up-to-date information on your parcel’s progress. We also offer notifications via email or SMS, so you can receive updates on your parcel’s status right to your phone." image="homepage/img-info-7.png" youtube_video_url="https://www.youtube.com/watch?v=v2qeqkKgw7U" button_label="We have 25 years experience in this passion" button_helper_text="There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour" button_icon="icons/play.png" style="style-3" quantity="4" title_1="Boost your sale" icon_1="icons/chart.png" description_1="The latest design trends meet hand-crafted templates." title_2="Boost your sale" icon_2="icons/chart.png" description_2="The latest design trends meet hand-crafted templates." title_3="Introducing New Features" icon_3="icons/feature.png" description_3="The latest design trends meet hand-crafted templates." title_4="Introducing New Features" icon_4="icons/feature2.png" description_4="The latest design trends meet hand-crafted templates."][/who-we-are]' .
                    '[brands title="We are trusted by major global brands" highlight_text="trusted" background_color="#E0F0F6" quantity="6" name_1="Alea" image_1="brands/alea.png" link_1="/contact-us" name_2="Creati" image_2="brands/creati.png" link_2="/contact-us" name_3="Land Ship" image_3="brands/land.png" link_3="/contact-us" name_4="Logis Delivery" image_4="brands/logis.png" link_4="/contact-us" name_5="Santos Logistic" image_5="brands/saltos.png" link_5="/contact-us" name_6="Truck" image_6="brands/truck.png" link_6="/contact-us"][/brands]' .
                    '[why-choose-us title="Why choose us" subtitle="Our Features" style="style-2" quantity="4" title_1="Over 1200 couriers" icon_1="icons/container.png" description_1="Global reach, over 1200 couriers forming a seamless network for worldwide deliveries." title_2="Automatic courier" icon_2="icons/24-hours.png" description_2="Efficiency amplified through automation, reducing human intervention for accuracy." title_3="Real-time alert" icon_3="icons/stopwatch.png" description_3="Stay informed with instant updates, tracking your shipment’s progress as it happens." title_4="Email alerts" icon_4="icons/pallet.png" description_4="Essential information directly to your inbox, ensuring you’re always in the loop."][/why-choose-us]' .
                    '[faqs title="FAQs" description="Feeling inquisitive? Have a read through some of our FAQs or contact our supporters for help." gallery_id="7" category_ids="1,2" expand_first_time="1" bottom_title="Need more help?" button_label="Contact Us" button_url="/contact-us" link_label="Learn More" link_url="/contact-us"][/faqs]' .
                    htmlentities('[who-we-are title="We are the world’s leading shipping service provider" subtitle="Who We Are?" description="Over the years, we have worked together to expand our network of partners to deliver reliability and consistency. We’ve also made significant strides to tightly integrate technology with our processes, giving our clients greater visibility into every engagement." image="homepage/img-info-6.png" youtube_video_url="https://www.youtube.com/watch?v=v2qeqkKgw7U" button_label="How it works ? <br> Watch video tour" button_icon="icons/play.png" style="style-2" quantity="4" title_1="Boost your sale" icon_1="icons/chart.png" description_1="The latest design trends meet hand-crafted templates." title_2="Boost your sale" icon_2="icons/chart.png" description_2="The latest design trends meet hand-crafted templates." title_3="Introducing New Features" icon_3="icons/feature.png" description_3="The latest design trends meet hand-crafted templates." title_4="Introducing New Features" icon_4="icons/feature2.png" description_4="The latest design trends meet hand-crafted templates."][/who-we-are]') .
                    '<div class="mt-90"></div>'
                ,
                'template' => 'default',
            ],
            [
                'name' => 'Work Process',
                'description' => 'You choose the cities where you’d like to deliver. All deliveries are within a specific service area and delivery services vary by location. Whatever the mode or requirement, we will find and book the ideal expedited shipping solution to ensure a timely delivery.',
                'template' => 'default',
                'metadata' => $stylePageDetail,
                'content' =>
                    '[how-it-works background_color="#034460" title_direction="start" youtube_video_url="https://www.youtube.com/watch?v=c8aOBRC3tvs" left_background="homepage/how-it-work.png" left_title="We have 25 years experience in this passion" left_description="There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour" left_icon="icons/play.png" style="style-1" quantity="5" title_1=" Customer places order" description_1="Inspection and quality check of goods" image_1="icons/order.png" title_2="Payment successful" description_2="Payoneer, Paypal, or Visa master card" image_2="icons/payment.png" title_3="Warehouse receives order" description_3="Check the accuracy of the goods." image_3="icons/warehouse.png" title_4="Item picked, packed & shipped" description_4="Ship the goods to a local carrier" image_4="icons/picked.png" title_5="Delivered & Measure success" description_5="Update order status on the system" image_5="icons/delivery.png"][/how-it-works]' .
                    '[our-process title="Our Process" description="We invest time and expertise to fully understand your business before designing plans to improve your supply chain. We take responsibility for the performance of all our suppliers and for ensuring the availability of resources and equipment needed to control the flow of goods under our charge." icon="general/favicon.png" quantity="4" title_1="Logistics Defined" description_1="Logistics is the planning framework used by the management of an organization to facilitate the distribution of personnel, materiel, service, information and capital flows." image_1="work-process/img1.png" icon_1="icons/parachute.png" link_label_1="View Details" link_url_1="/contact-us" title_2="Logistical Processes" description_2="Logistics is the planning framework used by the management of an organization to facilitate the distribution of personnel, materiel, service, information and capital flows." image_2="work-process/img2.png" icon_2="icons/pallet-2.png" link_label_2="View Details" link_url_2="/contact-us" title_3="Production Management" description_3="Logistics is the planning framework used by the management of an organization to facilitate the distribution of personnel, materiel, service, information and capital flows." image_3="work-process/img3.png" icon_3="icons/plane-2.png" link_label_3="View Details" link_url_3="/contact-us" title_4="Assembly Processing" description_4="Logistics is the planning framework used by the management of an organization to facilitate the distribution of personnel, materiel, service, information and capital flows." image_4="work-process/img4.png" icon_4="icons/cardboard.png" link_label_4="View Details" link_url_4="/contact-us"][/our-process]' .
                    '<div class="line-border mt-50"></div>' .
                    '[pricing title="Pricing Plan" description="Pick your plan. Change whenever you want. No switching fees between packages" style="style-2" package_ids="1,2,3,4" number_of_packages_per_line="4" left_background="backgrounds/bg-plan-left.png" right_background="backgrounds/bg-plan-right.png"][/pricing]' .
                    '[projects title="What We Have Done" description="Check out some of the projects we’ve completed with our amazing partners." button_label="View All Projects" button_url="/contact-us" background="shapes/bg-what-done.png" quantity="4" name_1="Air Freight" description_1="Our Air Freight project soared above expectations, showcasing our expertise in urgent deliveries. We provided rapid, global air transportation solutions that met critical timelines. When time is of the essence." image_1="homepage/img.png" url_1="/contact-us" name_2="Sea Freight" description_2="Our Sea Freight project stands as a testament to our proficiency in navigating international waters. Seamlessly managing complex logistics, we delivered goods across continents with efficiency and reliability." image_2="homepage/img2.png" url_2="/contact-us" name_3="Trucking" description_3="In our Trucking project, we transformed roadways into avenues of precision and punctuality. With a fleet of modern vehicles and a team of skilled drivers, we ensured swift and secure deliveries nationwide. Your cargo’s journey." image_3="homepage/img3.png" url_3="/contact-us" name_4="Warehouse" description_4="In our Warehouse project, we excelled in storage and distribution. With state-of-the-art facilities and meticulous inventory management, we safeguarded your assets while streamlining the supply chain. Your goods found." image_4="homepage/img4.png" url_4="/contact-us"][/projects]' .
                    '[why-choose-us title="Why choose us" subtitle="Our Features" description="Sustainability is an increasingly important factor for many customers when choosing a shipping company. Your shipping company can stand out by demonstrating a commitment to sustainable practices, such as using energy-efficient vehicles, reducing waste, and offsetting carbon emissions." ticked_line="Reliable and Timely Deliveries, Advanced Tracking Systems, Cost-Effective Shipping Options, Commitment to Sustainability, Exceptional Customer Service, International Shipping Expertise, Flexibility and Customization, Insurance and Liability Coverage" button_primary_label="Contact Us" button_primary_url="/contact-us" button_secondary_label="Learn More" button_secondary_url="/contact-us" style="style-1" quantity="4" title_1="Shipping Options" icon_1="icons/container.png" description_1="Tailored routes for versatile shipments, offering expedited and budget-friendly choices." title_2="Timely Deliveries" icon_2="icons/stopwatch.png" description_2="Precision planning and monitoring ensure on-time deliveries, a competitive edge for you." title_3="Customer Service" icon_3="icons/24-hours.png" description_3="Proactive solutions from our team, transforming challenges into satisfaction and support." title_4="Tracking Systems" icon_4="icons/pallet.png" description_4="Visibility at every stage, bridging distance through real-time insights for peace of mind."][/why-choose-us]'
                ,
            ],
            [
                'name' => 'Request a quote',
                'content' =>
                    htmlentities('[request-quote title="Request a quote for <br> shipping services" description="A big opportunity for your business growth. Delivering Results for Industry Leaders. We are <br> proud of our work for and have worked hard." background="backgrounds/requestaquote-banner.png" style="style-4" primary_button_label="Calculate Package" primary_button_url="/contact-us" secondary_button_label="How it work ?" secondary_button_icon="icons/play.png" secondary_button_url="https://www.youtube.com/watch?v=v2qeqkKgw7U" quantity="4" image_1="icons/handover.png" number_1="+ 380,000" title_1="Parcels Shipped Safely" image_2="icons/cities.png" number_2="+ 120,000" title_2="Cities Served Worldwide" image_3="icons/client.png" number_3="+2280" title_3="Satisfied Clients" image_4="icons/company.png" number_4="+ 1200" title_4="Company We Help" form_title="Calculate Shipping" form_description="Please Fill All Inquiry To Get Your Total Price." inner_background="shapes/bg-contact.png" form_background="homepage/img-contact.png" link_label="Contact Us" link_url="/contact-us"][/request-quote]') .
                    htmlentities('[branch-offices title="We have branches in many <br> regions of the world" description="We have experience in handling the formalities and documentation required for your imports and exports. We work with all international station to guarantee that your load will safely reach without any delays." button_label="Get a quote" button_url="/contact-us" quantity="4" image_1="contact/branch1.png" icon_1="icons/delivery.png" title_1="TransP Shipping Co. USA" address_1="123 Main Street, Suite 500, New York, NY 10001, USA" phone_number_1="+1-555-555-5555" email_1="contact@transp.eu.com" image_2="contact/branch2.png" icon_2="icons/plane.png" title_2="Shipping Co. Europe" address_2="25 Avenue des Champs-Élysées, Paris, France" phone_number_2="+33 1 55 73 70 00" email_2="contact.eu@transp.eu.com" image_3="contact/branch3.png" icon_3="icons/delivery.png" title_3="Shipping Co. Asia Pacific" address_3="1-2-1 Otemachi, Chiyoda-ku, Tokyo, Japan" phone_number_3="+81 3 5251 5300" email_3="contact.jp@transp.eu.com" image_4="contact/branch4.png" icon_4="icons/plane.png" title_4="Shipping Co. Middle East" address_4="Dubai Logistics City, Building B, Office 203, Dubai, UAE" phone_number_4="+971 4 887 8000" email_4="contact@transp.eu.com"][/branch-offices]') .
                    '[how-it-works title="How It Works" description="You choose the cities where you’d like to deliver. All deliveries are within a specific service area and delivery services vary by location. Whatever the mode or requirement, we will find and book the ideal expedited shipping solution to ensure a timely delivery." background_color="#034460" title_direction="start" youtube_video_url="https://www.youtube.com/watch?v=ldusxyoq0Y8" icon="general/favicon.png" inner_background="general/world-map.png" left_background="homepage/how-it-work.png" left_title="We have 25 years experience in this passion" left_description="There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour" left_icon="icons/play.png" style="style-1" quantity="5" title_1=" Customer places order" description_1="Inspection and quality check of goods" image_1="icons/order.png" title_2="Payment successful" description_2="Payoneer, Paypal, or Visa master card" image_2="icons/payment.png" title_3="Warehouse receives order" description_3="Check the accuracy of the goods." image_3="icons/warehouse.png" title_4="Item picked, packed & shipped" description_4="Ship the goods to a local carrier" image_4="icons/picked.png" title_5="Delivered & Measure success" description_5="Update order status on the system" image_5="icons/delivery.png"][/how-it-works]' .
                    '[pricing title="Pricing Plan" description="Pick your plan. Change whenever you want. No switching fees between packages" style="style-2" package_ids="1,2,3,4" number_of_packages_per_line="4" left_background="backgrounds/bg-plan-left.png" right_background="backgrounds/bg-plan-right.png"][/pricing]' .
                    '<div class="line-border"></div>' .
                    '[projects title="What We Have Done" description="Check out some of the projects we’ve completed with our amazing partners" button_label="View All Projects" button_url="/contact-us" style="style-1" quantity="4" name_1="Air Freight" description_1="Our Air Freight project soared above expectations, showcasing our expertise in urgent deliveries. We provided rapid, global air transportation solutions that met critical timelines. When time is of the essence." image_1="homepage/img.png" url_1="/contact-us" name_2="Sea Freight" description_2="Our Sea Freight project stands as a testament to our proficiency in navigating international waters. Seamlessly managing complex logistics, we delivered goods across continents with efficiency and reliability." image_2="homepage/img2.png" url_2="/contact-us" name_3="Trucking" description_3="In our Trucking project, we transformed roadways into avenues of precision and punctuality. With a fleet of modern vehicles and a team of skilled drivers, we ensured swift and secure deliveries nationwide. Your cargo’s journey." image_3="homepage/img3.png" url_3="/contact-us" name_4="Warehouse" description_4="In our Warehouse project, we excelled in storage and distribution. With state-of-the-art facilities and meticulous inventory management, we safeguarded your assets while streamlining the supply chain. Your goods found." image_4="homepage/img4.png" url_4="/contact-us"][/projects]' .
                    '<div class="mt-90"></div>'
                ,
                'template' => 'default',
            ],
            [
                'name' => 'Our team',
                'content' =>
                    '[hero-banner title="We’re excited to introduce you to the dedicated individuals who make up our logistics services company" subtitle="Meet Our Team" description="Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit laborum semper quis lectus nulla. Interactively transform magnetic growth strategies whereas prospective ‘‘outside the box’’ thinking." background_color="#E0F0F6" banner_image="homepage/img-testimonial-4.png" shape_icon="shapes/bg-testimonial-4.png" button_primary_url="/contact-us" button_primary_label="Contact Us" button_secondary_url="/about-us" button_secondary_label="Learn More" box_info_title="Satisfieds" box_info_description="We always strive to serve our customers in the best way." box_info_button_label="View Details" box_info_button_url="/contact-us" style="style-6" quantity="6"][/hero-banner]' .
                    '[teams title="Our Leadership Team" description="Welcome to our transportation services agency. We are the best at our transportation service ever." button_label="Get a quote" button_url="/contact-us" team_ids="1,2,3,4"][/teams]' .
                    htmlentities('[ads-banner title="Fast shipping with the <br> most modern technology" url="/contact-us" left_background="shapes/bg-banner.png" right_background="backgrounds/banner.png"][/ads-banner]') .
                    '[teams title="Our Operations Team" description="Welcome to our transportation services agency. We are the best at our transportation service ever." button_label="Get a quote" button_url="/contact-us" team_ids="1,2,3,4"][/teams]' .
                    '[who-we-are title="We are the world’s leading shipping service provider" subtitle="Who We Are?" description="Over the years, we have worked together to expand our network of partners to deliver reliability and consistency. We’ve also made significant strides to tightly integrate technology with our processes, giving our clients greater visibility into every engagement." image="homepage/img-info-6.png" youtube_video_url="https://www.youtube.com/watch?v=v2qeqkKgw7U" button_label="How it works ? Watch video tour" button_icon="icons/play.png" style="style-2" quantity="4" title_1="Boost your sale" icon_1="icons/chart.png" description_1="The latest design trends meet hand-crafted templates." title_2="Boost your sale" icon_2="icons/chart.png" description_2="The latest design trends meet hand-crafted templates." title_3="Introducing New Features" icon_3="icons/feature.png" description_3="The latest design trends meet hand-crafted templates." title_4="Introducing New Features" icon_4="icons/feature2.png" description_4="The latest design trends meet hand-crafted templates."][/who-we-are]' .
                    '<div class="mt-90"></div>'
                ,
                'template' => 'default',
            ],
            [
                'name' => 'FAQ’s',
                'template' => 'default',
                'metadata' => [
                    'breadcrumb' => 'style-1',
                    'breadcrumb_color' => '#e0f0f6',
                    'breadcrumb_background' => 'general/world-map.png',
                ],
                'content' =>
                    '[faqs title="Popular Topic" description="Feeling inquisitive? Have a read through some of our FAQs or contact our supporters for help." gallery_id="7" category_ids="1,2" expand_first_time="1" bottom_title="Need more help?" button_label="Contact Us" button_url="/contact-us" link_label="Learn More" link_url="/contact-us" style="style-2"][/faqs]' .
                    '[faqs title="FAQ’s" description="Feeling inquisitive? Have a read through some of our FAQs or contact our supporters for help." gallery_id="7" category_ids="1,2" expand_first_time="1" bottom_title="Need more help?" button_label="Contact Us" button_url="/contact-us" link_label="Learn More" link_url="/contact-us" style="style-1"][/faqs]' .
                    '[contact-form title="Still have question?" description="Can’t find the answer you are looking for? Please chat to our friendly team." title_button="Submit Now" subtitle="Headquarters" open_time="Hours: 8:00 - 17:00, Mon - Sat"][/contact-form]' .
                    htmlentities('[information-2 left_background="homepage/img-info-5.png" right_background="homepage/img-info-5-2.png" center_icon="icons/certified.png" title="Proud to Deliver <br> Excellence Every Time" badge_text="Get in touch" description="Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit laborum — semper quis lectus nulla. Interactively transform magnetic growth strategies whereas prospective ‘‘outside the box’’ thinking." button_label="Contact Us" button_url="/contact-us" link_label="Learn More" link_url="/contact-us" style="style-2" quantity="2" title_1="Boost your sale" image_1="icons/chart.png" description_1="The latest design trends meet hand-crafted templates." title_2="Introducing New Features" image_2="icons/feature.png" description_2="The latest design trends meet hand-crafted templates."][/information-2]')
                ,
                'description' => 'Everything you need to know about the product and billing. Can not find the answer you are looking for? Please Contact our support team.',
            ],
            [
                'name' => 'Newsletter',
                'content' =>
                    '[simple-slider key="home-slider"][/simple-slider]' .
                    '[services title="What We Offer" style="style-1" quantity="3" name_1="Sea Forwarding" image_1="icons/cargo-ship.png" description_1="We are professional in ocean freight with more than 12 years of experience and have shipped more than 100k shipments." link_1="/contact-us" name_2="Air Freight Forwarding" image_2="icons/plane.png" description_2="We are professional in ocean freight with more than 12 years of experience and have shipped more than 100k shipments." link_2="/contact-us" name_3="Land Transportation" image_3="icons/delivery.png" description_3="We are professional in ocean freight with more than 12 years of experience and have shipped more than 100k shipments." link_3="/contact-us"][/services]' .
                    '[information-1 left_background="homepage/img1.png" shape_image_horizontal="icons/icon1.png" shape_image_vertical="shapes/subtract.png" right_title="Fast shipping with the most modern technology" right_description="Over the years, we have worked together to expand our network of partners to deliver reliability and consistency." feature_1="Task tracking" feature_2="Create task dependencies" feature_3="Task visualization" feature_4="Hare files, discuss" feature_5="Meet deadlines faster" feature_6=" Track time spent" button_label_1="Apple Store" button_url_1="https://apps.apple.com/us/app/" button_image_1="general/appstore-btn.png" button_label_2="Google Play" button_url_2="https://play.google.com/store/apps" button_image_2="general/google-play-btn.png" style="style-1" quantity="6"][/information-1]' .
                    htmlentities('[information-2 left_background="homepage/img-info-5.png" right_background="homepage/img-info-5-2.png" center_icon="icons/certified.png" title="Proud to Deliver <br> Excellence Every Time" badge_text="Get in touch" description="Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit laborum — semper quis lectus nulla. Interactively transform magnetic growth strategies whereas prospective ‘‘outside the box’’ thinking." button_label="Contact Us" button_url="/contact-us" link_label="Learn More" link_url="/contact-us" style="style-2" quantity="1"][/information-2]') .
                    '[services title="Why Choose Us" style="style-2" quantity="4" name_1="Over 1200 couriers" image_1="icons/container.png" description_1="Global reach via 1200+ couriers, forming seamless worldwide delivery network for enhanced service." name_2="Automatic courier" image_2="icons/24-hours.png" description_2="Automated efficiency curbs intervention, upholding precision, speed & accuracy in worldwide deliveries." name_3="Real-time alert" image_3="icons/stopwatch.png" description_3="Stay updated with instant progress tracking, ensuring you‘re informed of developments as they unfold." name_4="Email alerts" image_4="icons/pallet.png" description_4="Essential updates sent directly, keeping you reliably informed and seamlessly connected at all times."][/services]' .
                    htmlentities('[information-2 left_background="shapes/bg-touch.png" right_background="homepage/port.png" title="Proud to Deliver <br> Excellence Every Time" badge_text="Get in touch" description="Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit laborum — semper quis lectus nulla. Interactively transform magnetic growth strategies whereas prospective ‘‘outside the box’’ thinking." button_label="Contact Us" button_url="/contact-us" link_label="Learn More" link_url="/contact-us" style="style-1" quantity="2" title_1="Boost your sale" image_1="icons/chart.png" description_1="The latest design trends meet hand-crafted templates." title_2="Introducing New Features" image_2="icons/feature3.png" description_2="The latest design trends meet hand-crafted templates."][/information-2]') .
                    '[teams title="Meet Our Team" team_ids="1,2,3,4"][/teams]' .
                    '[testimonials title="Testimonials" limit="4" shape_image="icons/quotation.png" style="style-3"][/testimonials]' .
                    '[request-quote style="style-2" quantity="1" form_title="Request a Quote" form_description="Please Fill All Inquiry To Get Your Total Price." link_label="Contact Us" link_url="/contact-us"][/request-quote]' .
                    '[news title="Our Blog & Insights" type="popular" limit="2"][/news]'
                ,
                'metadata' => [
                    'hide_pre_footer_sidebar' => true,
                ],
                'template' => 'default',
            ],
            [
                'name' => 'Blog',
                'content' =>
                    '[hero-banner title="Latest News & Blog" subtitle="Don’t miss the trending" description="Share discoveries on the world of Logistic, find curiosities about cargo services, produce insights on how intelligent agents work." banner_image="homepage/banner-5.png" shape_icon="icons/quote.png" style="style-5" quantity="6"][/hero-banner]' .
                    '[blog-posts category_ids="2,3,4,5,7"][/blog-posts]' .
                    htmlentities('[ads-banner title="Fast shipping with the <br> most modern technology" url="/contact-us" left_background="shapes/bg-banner.png" right_background="homepage/banner-ads.png"][/ads-banner]') .
                    '[posts per_page="5"][/posts]' .
                    '<div class="mt-70"></div>' .
                    '[brands title="We are trusted by major global brands" highlight_text="trusted" background_color="#E0F0F6" quantity="6" name_1="Alea" image_1="brands/alea.png" link_1="/contact-us" name_2="Creati" image_2="brands/creati.png" link_2="/contact-us" name_3="Land Ship" image_3="brands/land.png" link_3="/contact-us" name_4="Logis Delivery" image_4="brands/logis.png" link_4="/contact-us" name_5="Santos Logistic" image_5="brands/saltos.png" link_5="/contact-us" name_6="Truck" image_6="brands/truck.png" link_6="/contact-us"][/brands]' .
                    '<div class="mt-100"></div>'
                ,
                'template' => 'default',
            ],
            [
                'name' => 'Contact Us',
                'content' =>
                    '[map style="style-2"][/map]' .
                    '[contact-form title="Still have question?" description="Can’t find the answer you are looking for? Please chat to our friendly team." title_button="Submit Now" subtitle="Headquarters" address="4517 Washington Ave. Manchester, Kentucky 39495" phone="+01-246-357 (Any time 24/7)" email="contact@transp.eu.com" open_time="Hours: 8:00 - 17:00, Mon - Sat"][/contact-form]' .
                    htmlentities('[branch-offices title="We have branches in many <br> regions of the world" description="We have experience in handling the formalities and documentation required for your imports and exports. We work with all international station to guarantee that your load will safely reach without any delays." button_label="Get a quote" button_url="/contact-us" quantity="4" image_1="contact/branch1.png" icon_1="icons/delivery.png" title_1="TransP Shipping Co. USA" address_1="123 Main Street, Suite 500, New York, NY 10001, USA" phone_number_1="+1-555-555-5555" email_1="contact@transp.eu.com" image_2="contact/branch2.png" icon_2="icons/plane.png" title_2="Shipping Co. Europe" address_2="25 Avenue des Champs-Élysées, Paris, France" phone_number_2="+33 1 55 73 70 00" email_2="contact.eu@transp.eu.com" image_3="contact/branch3.png" icon_3="icons/delivery.png" title_3="Shipping Co. Asia Pacific" address_3="1-2-1 Otemachi, Chiyoda-ku, Tokyo, Japan" phone_number_3="+81 3 5251 5300" email_3="contact.jp@transp.eu.com" image_4="contact/branch4.png" icon_4="icons/plane.png" title_4="Shipping Co. Middle East" address_4="Dubai Logistics City, Building B, Office 203, Dubai, UAE" phone_number_4="+971 4 887 8000" email_4="contact@transp.eu.com"][/branch-offices]') .
                    '[teams title="Meet Our Team" description="Welcome to our transportation services agency. We are the best at our trans-deportation service ever." team_ids="1,2,3,4"][/teams]'
                ,
                'template' => 'default',
            ],
            [
                'name' => 'Coming Soon',
                'content' => htmlentities('[coming-soon title="Get Notified <br> When We Launch" time="2025-07-24" phone="+01-246-357 (Any time 24/7)" email="contact@transp.eu.com" image="general/coming-soon.png"][/coming-soon]'),
                'template' => 'default',
            ],
            [
                'name' => 'Privacy policy',
                'description' => 'We are committed to maintaining the accuracy, confidentiality, and security of your personally identifiable information Personal Information. As part of this commitment, our privacy policy governs our actions as they relate to the collection, use and disclosure of Personal Information.',
                'content' => File::get(database_path('seeders/contents/privacy-policy.html')),
                'metadata' => $stylePageDetail,
            ],
            [
                'name' => 'Cookies',
                'description' => 'Cookies are small text files that websites place and store on the computers and mobile devices of their users. These files are generally used to improve the user experience, but may contain personal information about the user or their behavior on the website.',
                'content' => File::get(database_path('seeders/contents/privacy-policy.html')),
                'metadata' => $stylePageDetail,
            ],
            [
                'name' => 'Terms of service',
                'description' => 'A well-written terms of service agreement can set the rules and guidelines for your users, prohibit or restrict certain behaviors and activities, limit your liabilities, and establish your property rights.',
                'content' => File::get(database_path('seeders/contents/privacy-policy.html')),
                'metadata' => $stylePageDetail,
            ],
        ];

        foreach ($pages as $item) {
            $item['user_id'] = 1;
            $page = Page::query()->create(Arr::except($item, ['metadata']));

            if (isset($item['metadata'])) {
                foreach ($item['metadata'] as $key => $value) {
                    MetaBox::saveMetaBoxData($page, $key, $value);
                }
            }

            SlugHelper::createSlug($page);
        }
    }
}
