@php Theme::layout('default');
@endphp

<div class="container">
    <div style="margin: 40px 0;">
        <h4 style="color: #f00; margin-bottom: 15px;">You need to setup your homepage first!</h4>

        <p><strong>1. Go to Admin -> Plugins then activate all plugins.</strong></p>
        <p><strong>2. Go to Admin -> Pages and create a page:</strong></p>

        <div style="margin: 20px 0;">
            <div>- Content:</div>
            <div style="border: 1px solid rgba(0,0,0,.1); padding: 10px; margin-top: 10px;direction: ltr;">
                <div>[simple-slider key="home-slider"][/simple-slider]</div>
                <div>[brands title="We are trusted by major global brands" highlight_text="trusted" background_color="#E0F0F6" quantity="6" name_1="Alea" image_1="brands/alea.png" link_1="/contact" name_2="Creati" image_2="brands/creati.png" link_2="/contact-us" name_3="Land Ship" image_3="brands/land.png" link_3="/contact-us" name_4="Logis Delivery" image_4="brands/logis.png" link_4="/contact-us" name_5="Santos Logistic" image_5="brands/saltos.png" link_5="/contact-us" name_6="Truck" image_6="brands/truck.png" link_6="/contact-us"][/brands]</div>
                <div>[services title="What We Offer" description="Welcome to our transportation services agency. We are the best at our transportation service ever." button_label="Get a quote" button_link="/contact-us" background="backgrounds/bg-offer.png" quantity="6" name_1="Sea Forwarding" image_1="icons/cargo-ship.png" description_1="We are professional in ocean freight with more than 12 years of experience and have shipped more than 100k shipments." link_1="/contact-us" name_2="Air Freight Forwarding" image_2="icons/plane.png" description_2="We are professional in ocean freight with more than 12 years of experience and have shipped more than 100k shipments." link_2="/contact-us" name_3="Land Transportation" image_3="icons/delivery.png" description_3="We are professional in ocean freight with more than 12 years of experience and have shipped more than 100k shipments." link_3="/contact-us" name_4="Warehouse & Distribution" image_4="icons/forklift.png" description_4="We are professional in ocean freight with more than 12 years of experience and have shipped more than 100k shipments." link_4="/contact-us" name_5="Railway Logistics" image_5="icons/train.png" description_5="We are professional in ocean freight with more than 12 years of experience and have shipped more than 100k shipments." link_5="/contact-us" name_6="Cross Border" image_6="icons/worldwide.png" description_6="We are professional in ocean freight with more than 12 years of experience and have shipped more than 100k shipments." link_6="/contact-us"][/services]</div>
                <div>[information-1 title="We are proud of our workforce <br> and have worked hard." subtitle="Delivering Results for Industry Leaders" icon="general/favicon.png" left_background="homepage/img1.png" shape_image_horizontal="icons/icon1.png" shape_image_vertical="shapes/subtract.png" right_title="Fast shipping with the most modern technology" right_description="Over the years, we have worked together to expand our network of partners to deliver reliability and consistency. We’ve also made significant strides to tightly integrate technology with our processes, giving our clients greater visibility into every engagement." feature_1="Task tracking" feature_2="Create task dependencies" feature_3="Task visualization" feature_4="hare files, discuss" feature_5="Meet deadlines faster" feature_6=" Track time spent on project" button_label_1="Apple Store" button_url_1="https://apps.apple.com/us/app/" button_image_1="general/appstore-btn.png" button_label_2="Google Play" button_url_2="https://play.google.com/store/apps" button_image_2="general/google-play-btn.png" style="style-1" quantity="6"][/information-1]</div>
                <div>[information-2 left_background="shapes/bg-touch.png" right_background="homepage/port.png" title="Proud to Deliver <br> Excellence Every Time" badge_text="Get in touch" description="Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit laborum — semper quis lectus nulla. Interactively transform magnetic growth strategies whereas prospective outside the box thinking." button_label="Contact Us" button_url="/contact-us" link_label="Learn More" link_url="/contact-us" quantity="2" text_1="Boost your sale" image_1="icons/chart.png" description_1="The latest design trends meet hand-crafted templates." text_2="Introducing New Features" image_2="icons/feature.png" description_2="The latest design trends meet hand-crafted templates."][/information-2]</div>
                <div>[how-it-works title="How It Works" description="You choose the cities where you’d like to deliver. All deliveries are within a specific service area and delivery services vary by location. Whatever the mode or requirement, we will find and book the ideal expedited shipping solution to ensure a timely delivery." background_color="#034460" title_direction="center" icon="general/favicon.png" inner_background="general/world-map.png" left_background="homepage/how-it-work.png" left_title="We have 25 years experience in this passion" left_description="There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour" left_icon="icons/play.png" style="style-1" quantity="5" title_1=" Customer places order" description_1="Inspection and quality check of goods" image_1="icons/order.png" title_2="Payment successful" description_2="Payoneer, Paypal, or Visa master card" image_2="icons/payment.png" title_3="Warehouse receives order" description_3="Check the accuracy of the goods." image_3="icons/warehouse.png" title_4="Item picked, packed & shipped" description_4="Ship the goods to a local carrier" image_4="icons/picked.png" title_5="Delivered & Measure success" description_5="Update order status on the system" image_5="icons/delivery-2.png"][/how-it-works]</div>
                <div>[testimonials title="What our customers are saying" description="Hear from our users who have saved thousands on their <br> Startup and SaaS solution spend." limit="4" background="homepage/ship.png" right_background="shapes/bg-testimonial.png" shape_image="icons/quotation.png"][/testimonials]</div>
                <div>[projects title="What We Have Done" description="Check out some of the projects we’ve completed with our amazing partners." button_label="View All Projects" button_url="/contact-us" background="shapes/bg-what-done.png" style="style-1" quantity="6" name_1="Air Freight" description_1="Aut ducimus inventore aut nihil exercitationem sed iure repellendus. Qui suscipit eaque aut necessitatibus quia ut expedita possimus. Sed consequatur consectetur ab fugit architecto" image_1="homepage/img.png" url_1="/contact" name_2="Sea Freight" description_2="Aut ducimus inventore aut nihil exercitationem sed iure repellendus. Qui suscipit eaque aut necessitatibus quia ut expedita possimus. Sed consequatur consectetur ab fugit architecto" image_2="homepage/img2.png" url_2="/contact-us" name_3="Trucking" description_3="Aut ducimus inventore aut nihil exercitationem sed iure repellendus. Qui suscipit eaque aut necessitatibus quia ut expedita possimus. Sed consequatur consectetur ab fugit architecto" image_3="homepage/img3.png" url_3="/contact-us" name_4="Warehouse" description_4="Aut ducimus inventore aut nihil exercitationem sed iure repellendus. Qui suscipit eaque aut necessitatibus quia ut expedita possimus. Sed consequatur consectetur ab fugit architecto" image_4="homepage/img4.png" url_4="/contact-us"][/projects]</div>
                <div>[request-quote title="World’s Leading Companies <br> For Over 80 Years." description="A big opportunity for your business growth. Delivering Results for Industry Leaders. We are <br> proud of our work for and have worked hard." background="homepage/container.png" quantity="4" image_1="icons/handover.png" number_1="+ 380,000" title_1="Parcels Shipped Safely" image_2="icons/cities.png" number_2="+ 120,000" title_2="Cities Served Worldwide" image_3="icons/client.png" number_3="+2280" title_3="Satisfied Clients" image_4="icons/company.png" number_4="+ 1200" title_4="Company We Help" form_title="Calculate Shipping" form_description="Please Fill All Inquiry To Get Your Total Price." inner_background="shapes/bg-contact.png" form_background="homepage/img-contact.png" link_label="Contact Us" link_url="/contact-us"][/request-quote]</div>
                <div>[pricing title="Choose The Best Plan" description="Pick your plan. Change whenever you want.<br>No switching fees between packages" style="style-1" package_ids="1,2,4" number_of_packages_per_line="3" left_background="backgrounds/bg-plan-left.png" right_background="backgrounds/bg-plan-right.png"][/pricing]</div>
                <div>[faqs title="FAQs" description="Feeling inquisitive? Have a read through some of our FAQs or contact our supporters for help." gallery_id="7" category_ids="1,2" expand_first_time="1" bottom_title="Need more help?" button_label="Contact Us" button_url="/contact-us" link_label="Learn More" link_url="/contact-us"][/faqs]</div>
                <div>[call-to-action title="Create your next Project with Us" subtitle="Have any ideas in your mind?" background="backgrounds/bg-get-quote.png" button_label="GET A QUOTE" button_url="/contact-us"][/call-to-action]</div>
                <div>[news title="Latest News" description="The latest information about shipping services and our promotions." type="latest"][/news]</div>
                <div>[call-to-action title="Create your next Project with Us" subtitle="Have any ideas in your mind?" background="backgrounds/bg-get-quote.png" button_label="GET A QUOTE" button_url="/contact-us"][/call-to-action]</div>
                <div>[map logo="general/logo.png" address="4517 Washington Ave. Manchester, Kentucky 39495" phone="+01-246-357 (Any time 24/7)" email="contact@transp.eu.com" opening_hours="Hours: 8:00 - 17:00, Mon - Sat"][/map]</div>
            </div>
            <br>
            <div>- Template: <strong>Homepage</strong>.</div>
        </div>

        <p><strong>3. Then go to Admin -> Appearance -> Theme options -> Page to set your homepage.</strong></p>
    </div>
</div>
